# Generated by Django 4.0.2 on 2022-02-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=150, unique=True)),
                ('value', models.TextField(blank=True, db_index=True, max_length=500)),
                ('date_pub', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
