# Generated by Django 4.0.2 on 2022-03-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, db_index=True, max_length=500)),
                ('title', models.CharField(db_index=True, max_length=150, unique=True)),
                ('link', models.CharField(db_index=True, max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, db_index=True, max_length=500)),
                ('title', models.CharField(db_index=True, max_length=150, unique=True)),
                ('link', models.CharField(db_index=True, max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('key', models.CharField(db_index=True, max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=80)),
                ('link', models.CharField(db_index=True, max_length=80, unique=True)),
                ('order', models.IntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='link',
            field=models.CharField(db_index=True, default='default link', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
