# Generated by Django 4.0.2 on 2022-03-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_rename_title_aboutusmodel_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='link',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='title',
        ),
        migrations.AddField(
            model_name='menu',
            name='value',
            field=models.TextField(blank=True, db_index=True, max_length=500),
        ),
    ]
