# Generated by Django 4.0.2 on 2022-03-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_remove_menu_link_remove_menu_order_remove_menu_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='link',
            field=models.CharField(db_index=True, default='', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
